// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.model.MuleKey", {
    extend: "Ext.data.Model",
    idProperty: "fullname",
    requires: ["Ext.data.NodeInterface"],
    fields: ["name", "fullname"],
    listeners: {
      append: function(me, node) {
        var fullname;
        fullname = node.getPath("name", ".").substring(".root.".length);
        return node.set("fullname", fullname);
      }
    }
  }, function() {
    return Ext.data.NodeInterface.decorate(this);
  });

}).call(this);
