FROM ubuntu:14.04

ENV lua_ver 5.3.2
ENV luarocks_ver 2.2.1
ENV lmdb_ver 0.9.17
ENV lightningmdb_ver 0.9.17.4-1

RUN apt-get update -y && apt-get install -y gcc libreadline-dev unzip curl make git

# Install lua
RUN cd /tmp && \
    curl -L -O http://www.lua.org/ftp/lua-${lua_ver}.tar.gz && \
    tar zxf lua-${lua_ver}.tar.gz && \
    rm lua-${lua_ver}.tar.gz && \
    cd lua-${lua_ver} && \
    make linux && \
    make install INSTALL_TOP=/usr && \
    cd /tmp && \
    rm -r /tmp/lua-${lua_ver}

# Install luarocks
RUN cd /tmp && \
    curl -L -O http://luarocks.org/releases/luarocks-${luarocks_ver}.tar.gz && \
    tar zxpf luarocks-${luarocks_ver}.tar.gz && \
    rm luarocks-${luarocks_ver}.tar.gz && \
    cd luarocks-${luarocks_ver} && \
    ./configure && \
    make bootstrap && \
    cd /tmp && \
    rm -r /tmp/luarocks-${luarocks_ver}


RUN cd /tmp && \
    curl -L -O https://github.com/LMDB/lmdb/archive/LMDB_${lmdb_ver}.tar.gz && \
    tar -xzf LMDB_${lmdb_ver}.tar.gz && \
    rm LMDB_${lmdb_ver}.tar.gz && \
    cd lmdb-LMDB_${lmdb_ver}/libraries/liblmdb && \
    make all install && \
    ldconfig && \
    cd /tmp && \
    rm -r /tmp/lmdb-LMDB_${lmdb_ver}


RUN luarocks install copas
RUN luarocks install lightningmdb
RUN luarocks install luaposix
RUN luarocks install lunitx
RUN luarocks install lsqlite3
RUN luarocks install xxhash

ENV HOME /root
WORKDIR $HOME

COPY *.lua $HOME/
COPY tests $HOME/tests
COPY fdi $HOME/fdi/
RUN mkdir -p $HOME/tests/temp

CMD lunit.sh tests/test_*.lua
