FROM ubuntu:14.04

RUN apt-get update -y && apt-get install -y gcc libreadline-dev unzip curl make git

# Install lua
RUN cd /tmp && \
    curl -L -O http://www.lua.org/ftp/lua-5.3.1.tar.gz && \
    tar zxf lua-5.3.1.tar.gz && \
    rm lua-5.3.1.tar.gz && \
    cd lua-5.3.1 && \
    make linux && \
    make install INSTALL_TOP=/usr && \
    cd /tmp && \
    rm -r /tmp/lua-5.3.1

# Install luarocks
RUN cd /tmp && \
    curl -L -O http://luarocks.org/releases/luarocks-2.2.1.tar.gz && \
    tar zxpf luarocks-2.2.1.tar.gz && \
    rm luarocks-2.2.1.tar.gz && \
    cd luarocks-2.2.1 && \
    ./configure --prefix=/usr && \
    make bootstrap && \
    cd /tmp && \
    rm -r /tmp/luarocks-2.2.1

RUN cd /tmp && \
    curl -L -O https://github.com/LMDB/lmdb/archive/LMDB_0.9.15.tar.gz && \
    tar -xzf LMDB_0.9.15.tar.gz && \
    rm LMDB_0.9.15.tar.gz && \
    cd lmdb-LMDB_0.9.15/libraries/liblmdb && \
    make all install && \
    ldconfig && \
    cd /tmp && \
    rm -r /tmp/lmdb-LMDB_0.9.15

RUN luarocks install copas 1.1.6-1
RUN luarocks install lightningmdb
RUN luarocks install luaposix
RUN luarocks install lunitx

ENV HOME /root
WORKDIR $HOME

COPY *.lua $HOME/
COPY tests $HOME/tests
COPY fdi $HOME/fdi/
RUN mkdir -p $HOME/tests/temp

CMD lunit.sh tests/test_*.lua
