// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.view.MuleLightChart", {
    extend: "Ext.panel.Panel",
    border: false,
    frame: false,
    layout: "fit",
    initComponent: function() {
      var _this = this;
      this.chart = Ext.create("Muleview.view.MuleChart", {
        data: this.data,
        keys: this.keys,
        store: this.store,
        topKey: this.topKey,
        legend: false,
        showAreas: false,
        highlight: false,
        timeLabel: {
          renderer: function() {
            return "";
          }
        }
      });
      ({
        adjustEnd: false
      });
      this.items = [this.chart];
      this.tools = [
        {
          type: "prev",
          handler: function() {
            return Muleview.event("graphRequest", Muleview.currentKey, _this.retention);
          }
        }
      ];
      return this.callParent();
    }
  });

}).call(this);
