// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.view.MuleChartPanel", {
    extend: "Ext.panel.Panel",
    layout: "fit",
    requires: ["Muleview.view.ZoomSlider", "Muleview.view.MuleChart"],
    initComponent: function() {
      var slider;
      this.chart = Ext.create("Muleview.view.MuleChart", {
        showAreas: true,
        keys: this.keys,
        topKey: this.topKey,
        alerts: this.alerts,
        store: this.store
      });
      this.items = [this.chart];
      this.bbar = {
        layout: {
          type: "hbox"
        },
        items: [
          slider = Ext.create("Muleview.view.ZoomSlider", {
            flex: 1,
            store: this.store
          }), {
            xtype: "button",
            text: "Reset",
            handler: function() {
              return slider.reset();
            }
          }
        ]
      };
      return this.callParent();
    }
  });

}).call(this);
