// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.view.MuleTimeField", {
    requires: ["Ext.tip.ToolTip"],
    alias: "widget.muletimefield",
    extend: "Ext.form.field.Text",
    regex: /^[0-9]+[mhsdy]?$/,
    toolTipHtml: "    You can use Mule's time format. <br/>    <u>Examples:</u><br/>    <ul>      <li>  20s</li>      <li>  5m</li>      <li>  3h</li>    </ul>        ",
    listeners: {
      afterrender: function(me) {
        return me.createTip();
      }
    },
    createTip: function() {
      return Ext.create("Ext.tip.ToolTip", {
        anchorSize: {
          height: 5,
          width: 10
        },
        anchorOffset: 10,
        anchorToTarget: true,
        defaultAlign: "r",
        target: this.getEl(),
        html: this.toolTipHtml,
        title: "Mule Time Format",
        anchor: "left",
        dismissDelay: 0
      });
    }
  });

}).call(this);
