// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.view.Viewport", {
    extend: "Ext.container.Viewport",
    layout: "border",
    requires: ["Muleview.view.AlertsEditor", "Ext.layout.container.Border", "Ext.tab.Panel", "Muleview.view.MuleChartPanel", "Muleview.view.MuleLightChart", "Ext.ux.statusbar.StatusBar"],
    items: [
      {
        id: "leftPanel",
        xtype: "panel",
        layout: "border",
        region: "west",
        width: "20%",
        split: true,
        collapsible: true,
        title: "Available Keys",
        items: [
          {
            xtype: "treepanel",
            region: "center",
            id: "keysTree",
            displayField: "name",
            rootVisible: false,
            lines: true
          }, {
            xtype: "tabpanel",
            region: "south",
            height: 280,
            split: "true",
            collapsible: true,
            collapsed: true,
            title: "Options",
            layout: "fit",
            items: [
              {
                xtype: "muleviewAlertsEditor",
                id: "alertsEditor"
              }, {
                xtype: "panel",
                layout: {
                  type: "hbox",
                  align: "middle",
                  pack: "center"
                },
                title: "Event Labels",
                items: [
                  {
                    xtype: "container",
                    html: "(Coming soon)"
                  }
                ]
              }
            ]
          }
        ]
      }, {
        id: "mainPanel",
        xtype: "tabpanel",
        title: "Main View",
        region: "center",
        layout: "fit",
        tools: [
          {
            type: "refresh",
            tooltip: "Reload Graphs",
            id: "mainPanelRefresh"
          }, {
            type: "maximize",
            tooltip: "Maximize Graph",
            id: "mainPanelMaximize"
          }, {
            type: "restore",
            tooltip: "Restore",
            id: "mainPanelRestore",
            hidden: true
          }
        ]
      }, {
        id: "rightPanel",
        width: "20%",
        split: true,
        xtype: "panel",
        region: "east",
        collapsible: true,
        title: "Previews",
        layout: {
          type: "vbox",
          align: "stretch"
        },
        defaults: {
          flex: 1
        }
      }, {
        xtype: "panel",
        layout: "fit",
        collapsible: true,
        collapsed: false,
        collapseMode: "mini",
        region: "south",
        header: false,
        height: 23,
        items: [
          {
            xtype: "statusbar",
            id: "statusBar",
            autoClear: 3000,
            defaultText: "Ready",
            items: [
              {
                xtype: "label",
                cls: "statusbar-text",
                id: "lastRefreshLabel"
              }, "-", {
                xtype: "tool",
                type: "minimize",
                tooltip: "Collapse status bar",
                handler: function(event, toolEl, owner) {
                  return owner.up().collapse();
                }
              }
            ]
          }
        ]
      }
    ]
  });

}).call(this);
