// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  Ext.define("Muleview.view.ZoomSlider", {
    extend: "Ext.slider.Multi",
    tipText: function(thumb) {
      return new Date(thumb.value * 1000);
    },
    listeners: {
      change: Ext.Function.createBuffered(function(me, newValue) {
        var max, min, _ref;
        _ref = me.getValues(), min = _ref[0], max = _ref[1];
        return me.store.filterBy(function(record) {
          var _ref1;
          return (min <= (_ref1 = record.get("timestamp")) && _ref1 <= max);
        });
      }, 100)
    },
    initComponent: function() {
      this.maxValue = this.store.max("timestamp");
      this.minValue = this.store.min("timestamp");
      this.increment = (this.maxValue - this.minValue) / 100;
      this.values = [this.minValue, this.maxValue];
      return this.callParent();
    }
  });

}).call(this);
