// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.Events", {
    singleton: true,
    mixins: {
      observable: "Ext.util.Observable"
    },
    constructor: function(config) {
      return this.mixins.observable.constructor.call(this, config);
    }
  });

}).call(this);
