// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.RefreshTimer", {
    singleton: true,
    requires: ["Muleview.Events", "Muleview.Settings"],
    constructor: function() {
      var _this = this;
      return window.setInterval(function() {
        return Muleview.event("refreshRequest");
      }, Muleview.Settings.updateInterval);
    }
  });

}).call(this);
