// Generated by CoffeeScript 1.6.1
(function() {

  Ext.define("Muleview.controller.History", {
    requires: ["Ext.util.History", "Muleview.Events"],
    gotoToken: function(token) {
      var key, retention, _ref;
      _ref = (token != null ? token : "").split(";"), key = _ref[0], retention = _ref[1];
      if (key) {
        return Muleview.event("graphRequest", key, retention);
      }
    },
    init: function() {},
    onLaunch: function() {
      var _this = this;
      return Ext.onReady(function() {
        Ext.util.History.init(function() {
          return Ext.util.History.on({
            change: _this.gotoToken,
            scope: _this
          });
        });
        return _this.gotoToken(Ext.util.History.getToken());
      });
    }
  });

}).call(this);
